CREATE TABLE "streaming" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" text NOT NULL,
  "description" text NOT NULL,
  "image" text,
  "alternative_local_titles" jsonb,
  "release_date" timestamp,
  "type" text NOT NULL,
  "genres" text[] NOT NULL,
  "audio_locales" text[] NOT NULL,
  "subtitle_locales" text[] NOT NULL,
  "content_provider" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE "season" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "streaming_id" integer NOT NULL,
  "title" text NOT NULL,
  "description" text NOT NULL,
  "total_episodes" integer,
  "release_date" timestamp,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE "episode" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "season_id" integer NOT NULL,
  "title" text NOT NULL,
  "metadata" jsonb NOT NULL,
  "release_date" timestamp,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE "episode_upload" (
  "episode_id" integer NOT NULL,
  "upload_process_id" UUID NOT NULL,
  PRIMARY KEY ("episode_id", "upload_process_id")
);

CREATE TABLE "upload_process" (
  "id" UUID PRIMARY KEY,
  "status" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now()
);

CREATE INDEX ON "season" ("streaming_id");

CREATE INDEX ON "episode" ("season_id");

ALTER TABLE "episode_upload" ADD FOREIGN KEY ("episode_id") REFERENCES "episode" ("id");

ALTER TABLE "episode_upload" ADD FOREIGN KEY ("upload_process_id") REFERENCES "upload_process" ("id");

ALTER TABLE "season" ADD FOREIGN KEY ("streaming_id") REFERENCES "streaming" ("id");

ALTER TABLE "episode" ADD FOREIGN KEY ("season_id") REFERENCES "season" ("id");
